name: resources
description: Resources module
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  intl: ^0.18.1
  intl_utils: ^2.8.4
  flutter_native_splash:
    git:
      url: https://github.com/lux-studio-66/flutter_native_splash.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  melos: ^3.1.1
  flutter_launcher_icons:
    path: ../flutter_launcher_icons-master

flutter_gen:
  output: lib/src/generated/assets

  # Optional
  integrations:
    flutter_svg: true

  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true

  fonts:
    enabled: true

flutter_intl:
  enabled: true
  class_name: Strings
  main_locale: vi
  output_dir: lib/src/generated/strings
  arb_dir: lib/src/strings

flutter:
  assets:
    - assets/pngs/
    - assets/svgs/
    #- images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
