name: app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  data:
    path: ../data
  domain:
    path: ../domain
  utilities:
    path: ../utilities
  configs:
    path: ../configs
  resources:
    path: ../resources
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.12.1
  firebase_storage: ^11.5.3
  injectable: ^2.3.0
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  auto_route: ^7.8.4
  flutter_form_bloc: ^0.31.0
  extended_image: ^8.1.1
  flutter_loadingindicator: ^1.0.1
  pull_to_refresh_flutter3: ^2.0.2
  flutter_speed_dial: ^7.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_sign_in: ^6.1.5
  flutter_countdown_timer: ^4.1.0
  google_sign_in_web: ^0.12.1
  google_sign_in_platform_interface: ^2.4.2
  flutter_spinkit: ^5.2.0
  select_dialog: ^2.0.1
  stream_transform: ^2.1.0
  socket_io_client: ^2.0.3+1
  flutter_link_previewer: ^3.2.2
  flutter_parsed_text: ^2.2.1
  url_launcher: ^6.2.1
  visibility_detector: ^0.4.0+2
  flutter_chat_types: ^3.6.2
  diffutil_dart: ^4.0.0
  scroll_to_index: ^3.0.1
  intl: ^0.18.1
  photo_view: ^0.14.0
  audioplayers: ^5.2.1
  video_player: ^2.8.1
  wechat_assets_picker: ^8.8.0
  wechat_camera_picker: ^4.1.1
  file_picker: ^6.1.1
  mime: ^1.0.4
  flutter_sound:
    git:
      url: https://github.com/quangnhat22/flutter_sound.git
      path: flutter_sound
      ref: master

  permission_handler: ^11.0.1
  path: ^1.8.3
  giphy_get: ^3.5.2
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  shimmer: ^3.0.0
  onesignal_flutter: ^5.0.4
  video_thumbnail: ^0.5.3
  open_filex: ^4.3.4
  http: ^1.1.0
  path_provider: ^2.1.1
  livekit_client: ^1.5.3
  flutter_webrtc: ^0.9.46
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0
  auto_route_generator: ^7.3.2
  hive_generator: ^2.0.1
  freezed: ^2.4.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
