name: app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  data:
    path: ../data
  domain:
    path: ../domain
  utilities:
    path: ../utilities
  configs:
    path: ../configs
  resources:
    path: ../resources
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  injectable: ^2.3.0
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  auto_route: ^7.8.4
  flutter_form_bloc: ^0.31.0
  extended_image: ^8.1.1
  flutter_loadingindicator: ^1.0.1
  pull_to_refresh_flutter3: ^2.0.2
  flutter_speed_dial: ^7.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_auth: ^4.12.1
  google_sign_in: ^6.1.5
  flutter_countdown_timer: ^4.1.0
  google_sign_in_web: ^0.12.1
  google_sign_in_platform_interface: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0
  auto_route_generator: ^7.3.2
  hive_generator: ^2.0.1
  freezed: ^2.4.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
